# Dev 分支推送部署预览
## 仅部署 Win 端
name: Build Dev

on:
  push:
    branches:
      - dev
      - master

jobs:
  release:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

       #安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: 查看结果
        run: |
          ls -l
          cp -r dist ../
          git branch dist 2>/dev/null  ##分支不存在用这个
          git checkout dist --
          rm -r * && rm -r .github && rm -r .vscode && rm -r .dockerignore && rm -r .env && rm -r .eslintignore && rm -r .eslintrc.json && rm -r  .gitignore && rm -r .hintrc && rm -r .prettierrc.json  
          sudo cp -r ../dist/* ./
          git config --global user.email "jadehh@live.com"
          git config --global user.name "jade"
          ls -l
          git add ./*
          git commit -a -m "update"
          git push --all --force


